### PR TITLE
fixes to Micromed reader class

### PR DESCRIPTION
**Pull request by bachsh**
- Moved private var initialization to init function.
- return_dat function now supports single channel (it used to fail)

### CODE REVIEW

**Comment by gpiantoni** [comment]
Thanks a lot! 

Any chance that you have a sample of a VWR file for testing purposes (the smaller the better)?

**Comment by bachsh** [comment]
I have a VWR file but it's large (25MB), and it has the patient's name inside. Do you know how to truncate and anonymize it?

**Comment by gpiantoni** [comment]
It's better not to send the file if it's not anonymized. If the VWR format is the same as TRC (which seems to be the case, right?), then there is no need for extra tests

**Comment by bachsh** [comment]
I cannot say for sure that it's the exact same format. I do know that I ran this code against a VWR file and was able to read the data.

**Pull request merged**
